In [1]:
# Predict Horse or Human
 
#Here we are loading train CNN model to predict Given input (image) is Horse of Human
 
# Import Libraries
 
# Load Liraries
import numpy as np
 
import keras 
from keras.preprocessing.image import ImageDataGenerator

In [2]:
"""# Import Model"""
 
model_path1 = '/content/drive/MyDrive/horse-or-human/horse_or_human_predictor.h5' #new model.ipynb
 
model1 = keras.models.load_model(model_path1)


In [3]:
"""#Preprocessing"""
 
#horse image path
h1 = '/content/drive/MyDrive/horse-or-human/test/horse/h1.jpg'
h2 = '/content/drive/MyDrive/horse-or-human/test/horse/h2.jpg'
h3 = '/content/drive/MyDrive/horse-or-human/test/horse/h3.jpg'
h4 = '/content/drive/MyDrive/horse-or-human/test/horse/h4.jpg'
h5 = '/content/drive/MyDrive/horse-or-human/test/horse/h5.jpg'
 
#human image path
hu1 = '/content/drive/MyDrive/horse-or-human/test/human/hu1.jpg'
hu2 = '/content/drive/MyDrive/horse-or-human/test/human/hu2.jpg'
hu3 = '/content/drive/MyDrive/horse-or-human/test/human/hu3.jpg'
hu4 = '/content/drive/MyDrive/horse-or-human/test/human/hu4.jpg'
hu5 = '/content/drive/MyDrive/horse-or-human/test/human/hu5.jpg'


In [4]:
import numpy as np
from keras.preprocessing import image
 
def pred_human_horse(model, horse_or_human):
  test_image = image.load_img(horse_or_human, target_size = (150, 150))
  test_image = image.img_to_array(test_image)/255
  test_image = np.expand_dims(test_image, axis = 0)
 
  result = model.predict(test_image).round(3)
 
  pred = np.argmax(result)
  print(result, "--->>>", pred)
 
  if pred == 0:
    print('Predicted>>> Horse')
  else:
    print('Predicted>>> Human')

# Predict Output

In [6]:
for horse_or_human in [h1,h2,h3,h4,h5, hu1,hu2,hu3,hu4,hu5]:
  pred_human_horse(model1, horse_or_human)


[[0.553 0.447]] --->>> 0
Predicted>>> Horse
[[0.429 0.571]] --->>> 1
Predicted>>> Human
[[0.49 0.51]] --->>> 1
Predicted>>> Human
[[0.437 0.563]] --->>> 1
Predicted>>> Human
[[0.326 0.674]] --->>> 1
Predicted>>> Human
[[0.615 0.385]] --->>> 0
Predicted>>> Horse
[[0.608 0.392]] --->>> 0
Predicted>>> Horse
[[0.542 0.458]] --->>> 0
Predicted>>> Horse
[[0.568 0.432]] --->>> 0
Predicted>>> Horse
[[0.439 0.561]] --->>> 1
Predicted>>> Human
